title: Ensemble Meliora
description: NYC early music ensemble
theme: minima

baseurl: "/"

minima:
  include_custom_css: true

header_pages:
  - about.md
  - members.md
  - schedule.md
  - watch_listen.md
  - contact.md

